In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("cleaned_data.csv")

In [4]:
df.head(10)

,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date
0,FAQ,1000,2100,1550,2020-01-09
1,FAQ,700,1500,1100,2020-01-10
2,FAQ,700,1700,1200,2020-01-13
3,FAQ,700,1400,1050,2020-01-17
4,FAQ,600,1500,1050,2020-01-20
5,FAQ,400,1400,900,2020-01-21
6,FAQ,600,1000,800,2020-01-24
7,FAQ,500,900,700,2020-01-29
8,FAQ,500,1000,750,2020-02-03
9,FAQ,500,900,700,2020-02-13

now creating lag prices for future prediction

In [7]:
df["lag_1"]=df["Modal Price (Rs./Quintal)"].shift(1)

In [8]:
df

,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,lag_1
0,FAQ,1000,2100,1550,2020-01-09,NaN
1,FAQ,700,1500,1100,2020-01-10,1550.0
2,FAQ,700,1700,1200,2020-01-13,1100.0
3,FAQ,700,1400,1050,2020-01-17,1200.0
4,FAQ,600,1500,1050,2020-01-20,1050.0
...,...,...,...,...,...,...
566,FAQ,4200,4800,4500,2025-07-29,4500.0
567,FAQ,4400,4800,4600,2025-07-30,4500.0
568,FAQ,4000,4800,4400,2025-08-01,4600.0
569,FAQ,4500,4800,4650,2025-08-08,4400.0
570,FAQ,4500,4800,4650,2025-08-11,4650.0

In [14]:
df["lag_2"]=df["Modal Price (Rs./Quintal)"].shift(2)
df["lag_3"]=df["Modal Price (Rs./Quintal)"].shift(3)

In [16]:
df

,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,lag_1,lag_2,lag_3
0,FAQ,1000,2100,1550,2020-01-09,NaN,NaN,NaN
1,FAQ,700,1500,1100,2020-01-10,1550.0,NaN,NaN
2,FAQ,700,1700,1200,2020-01-13,1100.0,1550.0,NaN
3,FAQ,700,1400,1050,2020-01-17,1200.0,1100.0,1550.0
4,FAQ,600,1500,1050,2020-01-20,1050.0,1200.0,1100.0
...,...,...,...,...,...,...,...,...
566,FAQ,4200,4800,4500,2025-07-29,4500.0,3250.0,4150.0
567,FAQ,4400,4800,4600,2025-07-30,4500.0,4500.0,3250.0
568,FAQ,4000,4800,4400,2025-08-01,4600.0,4500.0,4500.0
569,FAQ,4500,4800,4650,2025-08-08,4400.0,4600.0,4500.0
570,FAQ,4500,4800,4650,2025-08-11,4650.0,4400.0,4600.0

In [19]:
# adding moving averages
df["ma_3"]=df["Modal Price (Rs./Quintal)"].rolling(window=3).mean() ## mean of 3 date model price consicutively

In [21]:
df

,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,lag_1,lag_2,lag_3,ma_3
0,FAQ,1000,2100,1550,2020-01-09,NaN,NaN,NaN,NaN
1,FAQ,700,1500,1100,2020-01-10,1550.0,NaN,NaN,NaN
2,FAQ,700,1700,1200,2020-01-13,1100.0,1550.0,NaN,1283.333333
3,FAQ,700,1400,1050,2020-01-17,1200.0,1100.0,1550.0,1116.666667
4,FAQ,600,1500,1050,2020-01-20,1050.0,1200.0,1100.0,1100.000000
...,...,...,...,...,...,...,...,...,...
566,FAQ,4200,4800,4500,2025-07-29,4500.0,3250.0,4150.0,4083.333333
567,FAQ,4400,4800,4600,2025-07-30,4500.0,4500.0,3250.0,4533.333333
568,FAQ,4000,4800,4400,2025-08-01,4600.0,4500.0,4500.0,4500.000000
569,FAQ,4500,4800,4650,2025-08-08,4400.0,4600.0,4500.0,4550.000000
570,FAQ,4500,4800,4650,2025-08-11,4650.0,4400.0,4600.0,4566.666667

In [23]:
df["ma_7"]=df["Modal Price (Rs./Quintal)"].rolling(window=7).mean()

In [25]:
df

,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,lag_1,lag_2,lag_3,ma_3,ma_7
0,FAQ,1000,2100,1550,2020-01-09,NaN,NaN,NaN,NaN,NaN
1,FAQ,700,1500,1100,2020-01-10,1550.0,NaN,NaN,NaN,NaN
2,FAQ,700,1700,1200,2020-01-13,1100.0,1550.0,NaN,1283.333333,NaN
3,FAQ,700,1400,1050,2020-01-17,1200.0,1100.0,1550.0,1116.666667,NaN
4,FAQ,600,1500,1050,2020-01-20,1050.0,1200.0,1100.0,1100.000000,NaN
...,...,...,...,...,...,...,...,...,...,...
566,FAQ,4200,4800,4500,2025-07-29,4500.0,3250.0,4150.0,4083.333333,3792.857143
567,FAQ,4400,4800,4600,2025-07-30,4500.0,4500.0,3250.0,4533.333333,3978.571429
568,FAQ,4000,4800,4400,2025-08-01,4600.0,4500.0,4500.0,4500.000000,4128.571429
569,FAQ,4500,4800,4650,2025-08-08,4400.0,4600.0,4500.0,4550.000000,4292.857143
570,FAQ,4500,4800,4650,2025-08-11,4650.0,4400.0,4600.0,4566.666667,4364.285714

In [27]:
df.fillna({'lag_1': df["Modal Price (Rs./Quintal)"],'lag_2':df["Modal Price (Rs./Quintal)"],'lag_3':df["Modal Price (Rs./Quintal)"],'ma_3':df["Modal Price (Rs./Quintal)"],'ma_7':df["Modal Price (Rs./Quintal)"]},inplace=True)

In [29]:
df

,Grade,Min Price (Rs./Quintal),Max Price (Rs./Quintal),Modal Price (Rs./Quintal),Price Date,lag_1,lag_2,lag_3,ma_3,ma_7
0,FAQ,1000,2100,1550,2020-01-09,1550.0,1550.0,1550.0,1550.000000,1550.000000
1,FAQ,700,1500,1100,2020-01-10,1550.0,1100.0,1100.0,1100.000000,1100.000000
2,FAQ,700,1700,1200,2020-01-13,1100.0,1550.0,1200.0,1283.333333,1200.000000
3,FAQ,700,1400,1050,2020-01-17,1200.0,1100.0,1550.0,1116.666667,1050.000000
4,FAQ,600,1500,1050,2020-01-20,1050.0,1200.0,1100.0,1100.000000,1050.000000
...,...,...,...,...,...,...,...,...,...,...
566,FAQ,4200,4800,4500,2025-07-29,4500.0,3250.0,4150.0,4083.333333,3792.857143
567,FAQ,4400,4800,4600,2025-07-30,4500.0,4500.0,3250.0,4533.333333,3978.571429
568,FAQ,4000,4800,4400,2025-08-01,4600.0,4500.0,4500.0,4500.000000,4128.571429
569,FAQ,4500,4800,4650,2025-08-08,4400.0,4600.0,4500.0,4550.000000,4292.857143
570,FAQ,4500,4800,4650,2025-08-11,4650.0,4400.0,4600.0,4566.666667,4364.285714

Without lag/rolling features, the model only sees "today’s price" and maybe the date. It can’t learn how the market behaves over time.
Lagging = short-term memory
Rolling = trend + stability measure

so now instand of date we can relay on new feature with smooth shifting of data

In [34]:
df.columns

Index(['Grade', 'Min Price (Rs./Quintal)', 'Max Price (Rs./Quintal)',
       'Modal Price (Rs./Quintal)', 'Price Date', 'lag_1', 'lag_2', 'lag_3',
       'ma_3', 'ma_7'],
      dtype='object')

In [36]:
X = df.drop(columns=["Modal Price (Rs./Quintal)", "Min Price (Rs./Quintal)", "Max Price (Rs./Quintal)", "Price Date"])
y = df["Modal Price (Rs./Quintal)"]

In [38]:
X=X.drop("Grade",axis=1)

In [40]:
y

0      1550
1      1100
2      1200
3      1050
4      1050
       ...
566    4500
567    4600
568    4400
569    4650
570    4650
Name: Modal Price (Rs./Quintal), Length: 571, dtype: int64

In [42]:
#features=X.columns

In [44]:
#X=pd.get_dummies(X[features])

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,shuffle=False)

In [48]:
x_train

      lag_1   lag_2   lag_3         ma_3         ma_7
0    1550.0  1550.0  1550.0  1550.000000  1550.000000
1    1550.0  1100.0  1100.0  1100.000000  1100.000000
2    1100.0  1550.0  1200.0  1283.333333  1200.000000
3    1200.0  1100.0  1550.0  1116.666667  1050.000000
4    1050.0  1200.0  1100.0  1100.000000  1050.000000
..      ...     ...     ...          ...          ...
451  1000.0  1200.0  1000.0   916.666667  1092.857143
452   550.0  1000.0  1200.0   700.000000   942.857143
453   550.0   550.0  1000.0   683.333333   892.857143
454   950.0   550.0   550.0   833.333333   892.857143
455  1000.0   950.0   550.0   983.333333   892.857143

[456 rows x 5 columns]

In [49]:
y_train

0      1550
1      1100
2      1200
3      1050
4      1050
       ...
451     550
452     550
453     950
454    1000
455    1000
Name: Modal Price (Rs./Quintal), Length: 456, dtype: int64

In [51]:
from sklearn.linear_model import LinearRegression

In [52]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [53]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [54]:
y_pred_lr = lr.predict(x_test)

print("Linear Regression Performance:")
print(f"MAE: {mean_absolute_error(y_test, y_pred_lr):.2f}")
print(f"RMSE: {mean_squared_error(y_test, y_pred_lr):.2f}")
print(f"R²: {r2_score(y_test, y_pred_lr):.2f}")

Linear Regression Performance:
MAE: 1.59
RMSE: 3.35
R²: 1.00

In [55]:
rf=RandomForestRegressor(n_estimators=200,random_state=123)

In [56]:
rf.fit(x_train,y_train)

RandomForestRegressor(n_estimators=200, random_state=123)

In [61]:
y_pred_rf=rf.predict(x_test)
print("Random Forest Performance:")
print(f"MAE: {mean_absolute_error(y_test, y_pred_rf):.2f}")
print(f"RMSE: {mean_squared_error(y_test, y_pred_rf):.2f}")
print(f"R²: {r2_score(y_test, y_pred_rf):.2f}")

Random Forest Performance:
MAE: 91.90
RMSE: 22192.99
R²: 0.99

In [63]:
import joblib
joblib.dump(rf, "best_price_model.pkl")

['best_price_model.pkl']